### ISSUE TITLE
Campo telefono tabla monitores y socios

### ISSUE THREAD

**Issue by AntonioDuprez** [AntonioDuprez/delonetServer#10]
El campo telefono de la tabla monitores es de tipo VARCHAR, pero en la tabla socios y tal cual lo tenemos programado lo interpretamos como un NUMBER.

Cambiar este campo a tipo NUMBER en la tabla monitores. Sino podría darnos fallo con las APIS.

**Comment by AntonioDuprez** [comment]
Oh wait, no, ambos están como varchar, estoy mirando el último sql que pasaste.
Pero en la INSERCIÓN de datos, el telefono de socios va entre comillas ('') y el de monitores normal.

````
/***********************/
/* TABLA: socios       */
/***********************/

INSERT INTO socios (nombre, apellidos, direccion, fecha_alta, fecha_baja, telefono, id_clase, email)
VALUES ('Juan', 'Martin', 'C/ Laujar de Andarax 37, Vicar', '2018/06/02', '2018/07/02', '666112233', 7, 'juan@gmail.com'),
('Antonio', 'Duprez', 'C/ Costa Blanca 11, Aguadulce', '2018/06/15', '2018/07/15', '666445566', 5, 'antonio@gmail.com'),
('Alicia', 'Rodriguez', 'C/ Blanca 6, Aguadulce', '2018/06/28', '2018/07/28', '612345678', 2, 'alicia@gmail.com'),
('Fran', 'Ruiz', 'C/ Verde 12, Almeria', '2018/06/25', '2018/07/25', '601234567', 7, 'fran@gmail.com'),
('Estefanía', 'Padilla', 'C/ Rojo 43, Vicar', '2018/06/11', '2018/07/11', '656789812', 5, 'estefania@gmail.com'),
('Jose', 'Díaz', 'C/ Amarilla 15, El Ejido', '2018/06/06', '2018/07/06', '654267111', 1, 'jose@gmail.com');


/***********************/
/* TABLA: monitores    */
/***********************/

INSERT INTO monitores (nombre, apellidos, direccion, telefono, email)
VALUES ('Adrián', 'Roda', 'C/ Ancha 12, Vícar', 612345122, 'adrian@delonet.com'),
('Laura', 'Alcántara', 'C/ Estrecha 27, Vícar', 678568765, 'laura@delonet.com'),
('Gabriel', 'Manzano', 'C/ Intermedia 7, Vícar', 609675493, 'gabriel@delonet.com');
````


Esto creo que lo he habado con rafa, y lo que me ha dicho, y me habia dicho algo que realmente daba igual el tipo del que fuese lo que le diesemos desde el front (string o number), que mysql si se lo pasabas entre comillas (''), lo interpretaba posteriormente como el tipo de dato que tu le hubieses puesto el DB.

Osea lo mismo no petaba por eso, y petaba por la longitud del telefono, no lo se, esta tarde lo miramos.

-------------------------------------------------------------

Dejo tema abierto para acordarnos.

**Comment by JuanMME** [comment]
He modificado el sql, ahora ambos son varchar. No veo necesidad de pasarlos a number ya que no es un dato con el que se vayan a realizar operaciones matemáticas. Si necesitas que ambos sean number por algún motivo avisa y lo cambio.
