### ISSUE TITLE
Get con id

### ISSUE THREAD

**Issue by JuanMME** [AntonioDuprez/delonetServer#14]
Propongo cambiar todos los get a los que se les pasa un id para que devuelvan data[0] en la respuesta, de forma que devuelvan un "objeto" sin más en vez de un array con solo una posición con el objeto dentro. La parte de front queda más limpia así. Si me das el ok lo cambio yo mismo en todos, te pregunto porque no se hasta que punto te jode en la parte que ya está hecha de admin en la app.

**Comment by AntonioDuprez** [comment]
No entiendo para que quieres eso, ni de que forma quedaria más limpia, explica mejor y dime que estructura quedaria completamente?

**Comment by JuanMME** [comment]
Tal y como está ahora si tu haces un get con id y haces algo tipo:

<pre>this._reservationsService.getClass(event).subscribe(clase => {
    this.clase = clase
});</pre>

Osea, un get a reservas pasando un id, lo que te devuelve no es una clase realmente, es un array con solo una posición y en ella está la clase. te devuelve un json igual que el get normal pero solo con una posición. Me gustaría que en vez de un array devolviese el objeto sin más, es más cómodo para trabajar.

Ahora devuelve:

<pre></pre>

**Comment by AntonioDuprez** [comment]
Ah vale, dale claro eso no hace falta que ni lo preguntes
